version: 2.1

orbs:
  node: circleci/node@5.0.2

jobs:
  lint_code:
    executor: node/default
    description: Lint code
    steps:
      - checkout
      - node/install-packages
      - run:
          name: Lint code
          command: npm run lint:fix
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  run_tests:
    executor: node/default
    description: Run tests
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Run tests
          command: npm run test
          working_directory: ~/project
  build:
    executor: node/default
    description: Build
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Build
          command: npm run build
  run_release:
    executor: node/default
    description: Run release
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Set up git credentials
          command: |
            git config --global user.email $GIT_EMAIL
            git config --global user.name $GIT_NAME
      - run:
          name: Run release
          command: npm run release
  publish_to_npm:
    executor: node/default
    description: Publish to npm
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Login to npm
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Publish to npm
          command: npm publish
          environment:
            NPM_TOKEN: $NPM_TOKEN

workflows:
  build_app:
    jobs:
      - lint_code
      - run_tests:
          requires:
            - lint_code
      - build:
          requires:
            - run_tests
      - run_release:
          requires:
            - build
      - publish_to_npm:
          requires:
            - run_release
